import Navbar from "../components/navbar"
import AuthContext from "../components/AuthContext"
import Layout from "../components/layout"
import getBrandsData from "../lib/getBrandsData"
import getCategoryData from "../lib/getCategoryData"
import Footer from "../components/footer"
import './styles/global.css'
import { getSession } from "next-auth/react"
import getSessionData from "../lib/getSessionData"
import NextAuth from "next-auth/next"
import { getServerSession } from "next-auth"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const pageData = getCategoryData()
  const data = await pageData

  const brandsData = getBrandsData()
  const brands_data = await brandsData
  const session = await getSession()

  return (
    <html lang="en">
      <body>
        <AuthContext>
          <Layout data={data} brands_data={brands_data} sessionServ={session} >
            {children}
          </Layout>
        </AuthContext>
      </body>
    </html >
  )
}
